image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_tags: true

install:
  - ps: $env:version_file_path = ".\version.props"
  - ps: gitversion /output buildserver
  - ps: $env:major_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:minor_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:release_version = [string]([int]((Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText) + 1)
  - ps: $env:revision = $env:GitVersion_CommitsSinceVersionSource
  - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:revision"
  - ps: $xReleaseVersion = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/ReleaseVersion"
  - ps: $xReleaseVersion.Node.InnerText = $env:release_version
  - ps: $xReleaseVersion.Node.OwnerDocument.Save($xReleaseVersion.Path)
  - ps: $xRevision = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/Revision"
  - ps: $xRevision.Node.InnerText = $env:revision
  - ps: $xRevision.Node.OwnerDocument.Save($xRevision.Path)

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore "source\Common.sln"

build:
  project: source\Common.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: scripts\InstallTestAssemblies.bat

after_test:
  - cmd: scripts\UninstallTestAssemblies.bat

artifacts:
- path: 'bin\Release\EnterpriseLibrary.Common.*.nupkg'
  name: 'EnterpriseLibrary.Common'

on_success:
  - ps: git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
  - ps: git config --global user.email "$env:github_email"
  - ps: git config --global user.name "$env:github_name"
  - ps: git pull
  - git commit -m "Revision update by AppVeyor [ci skip]" -- version.props
  - git push